from .f_aras import fARAS
from .f_cocoso import fCOCOSO
from .f_codas import fCODAS
from .f_copras import fCOPRAS
from .f_edas import fEDAS
from .f_mabac import fMABAC
from .f_mairca import fMAIRCA
from .f_moora import fMOORA
from .f_spotis import fSPOTIS
from .f_ocra import fOCRA
from .f_topsis import fTOPSIS
from .f_vikor import fVIKOR
from .f_waspas import fWASPAS
from .f_wpm import fWPM
from .f_wsm import fWSM
from .utils import *
